// projectplan/src/pages/Login.jsx
import React from 'react'

function Login() {
  return (
    <div className="container-fluid page-body-wrapper full-page-wrapper">
    <div className="content-wrapper d-flex align-items-center auth px-0">
      <div className="row w-100 mx-0">
        <div className="col-lg-4 mx-auto">
          <div className="auth-form-light text-left py-5 px-4 px-sm-5">
            <div className="brand-logo">
              <img src="/images/logo.svg" alt="logo"></img>
            </div>
            <h4>Hello! let's get started</h4>
            <h6 className="font-weight-light">Sign in to continue.</h6>
            <form className="pt-3">
              <div className="form-group">
                <input type="email" className="form-control form-control-lg" id="exampleInputEmail1" placeholder="Username"></input>
              </div>
              <div className="form-group">
                <input type="password" className="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password"></input>
              </div>
              <div className="mt-3">
                <a className="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" href="../../index.html">SIGN IN</a>
              </div>
              <div className="my-2 d-flex justify-content-between align-items-center">
                <div className="form-check">
                  <label className="form-check-label text-muted">
                    <input type="checkbox" className="form-check-input"></input>
                    Keep me signed in
                  </label>
                </div>
                <a href="#" className="auth-link text-black">Forgot password?</a>
              </div>
              <div className="mb-2">
                <button type="button" className="btn btn-block btn-facebook auth-form-btn">
                  <i className="mdi mdi-facebook me-2"></i>Connect using facebook
                </button>
              </div>
              <div className="text-center mt-4 font-weight-light">
                Don't have an account? <a href="register.html" className="text-primary">Create</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

  </div>
  )
}

export default Login

// ProjectStatus/src/app/components/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { TitleService } from 'src/app/services/title.service';
import { SITE_NAME } from 'src/app/utilities/constants/common';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent implements OnInit {
  title = 'Login';  
  SITE_NAME=SITE_NAME;
  constructor(private titleService: TitleService) {
    this.titleService.setTitle(this.title);
  }

  ngOnInit(): void {}
}

<div class="container-fluid page-body-wrapper full-page-wrapper">
    <div class="content-wrapper d-flex align-items-center auth px-0">

        <div class="row w-100 mx-0">
            <div class="col-lg-4 mx-auto">
                <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                    <div class="brand-logo">
                        <img src="assets/images/logo.svg" alt="logo">
                    </div>
                    <h4>{{SITE_NAME}}</h4>
                    <h6 class="font-weight-light">{{title}} in to continue.</h6>
                    <form class="pt-3">
                         <div class="form-group">
                            <input type="email" class="form-control" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password">
                        </div>
                        <div class="form-group mt-3">
                            <button type="button" class="btn btn-primary btn-block">Primary</button> 
                        </div>
                        <!-- <div class="my-2 d-flex justify-content-between align-items-center">
                            <div class="form-check">
                                <label class="form-check-label text-muted">
                                    <input type="checkbox" class="form-check-input">
                                    Keep me signed in
                                </label>
                            </div>
                            <a href="#" class="auth-link text-black">Forgot password?</a>
                        </div>
                        <div class="mb-2">
                            <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                                <i class="mdi mdi-facebook me-2"></i>Connect using facebook
                            </button>
                        </div>
                        <div class="text-center mt-4 font-weight-light">
                            Don't have an account? <a href="register.html" class="text-primary">Create</a>
                        </div> -->
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
